import type { InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Augmenter, composeAugmenters } from '../src/augmenters'
import styles from '../styles/Home.module.css'

export const aug1: Augmenter<
  { more: string; },
  { title: string; }
> = fn => async context => {
  const res = await fn({ ...context, more: 'contextData'  });
  if ('props' in res) {
    const currProps = await res.props;
    return {
      props: {
        ...currProps,
        title: "SS Compose"
      },
    };
  }
  
  return res;
};




export const aug2: Augmenter<
  { extra: string; }
> = fn => async context => {
  return fn({ ...context, extra: 'contextData' });
};

export const getServerSideProps = composeAugmenters(aug1, aug2)(async (context) => {
    console.log(context.extra)
    console.log(context.more)
  return {
    props: {foo:'bar'}
  }
})


const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {props.title}
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
